CREATE DATABASE BD_Crud;
USE BD_Crud;
CREATE TABLE TB_ESTADO(
   ID_EST INT PRIMARY KEY AUTO_INCREMENT,
   NOME_EST VARCHAR(100)
);

INSERT INTO TB_ESTADO (NOME_EST)
VALUE ('Acre (AC)'),
('Alagoas (AL)'),
('Amapá (AP)'),
('Amazonas (AM)'),
('Bahia (BA)'),
('Ceará (CE)'),
('Distrito Federal (DF)'),
('Espírito Santo (ES)'),
('Goiás (GO)'),
('Maranhão (MA)'),
('Mato Grosso (MT)'),
('Mato Grosso do Sul (MS)'),
('Minas Gerais (MG)'),
('Pará (PA)'),
('Paraíba (PB)'),
('Paraná (PR)'),
('Pernambuco (PE)'),
('Piauí (PI)'),
('Rio de Janeiro (RJ)'),
('Rio Grande do Norte (RN)'),
('Rio Grande do Sul (RS)'),
('Rondônia (RO)'),
('Roraima (RR)'),
('Santa Catarina (SC)'),
('São Paulo (SP)'),
('Sergipe (SE)'),
('Tocantins (TO)');
SELECT * FROM TB_ESTADO;
CREATE TABLE TB_TIPO(
   ID_TIPO INT PRIMARY KEY AUTO_INCREMENT,
   NOME_TIPO VARCHAR(100)
);
INSERT INTO TB_TIPO (NOME_TIPO)
VALUE ('Eletronico'),
('Cosmeticos'),
('Roupa'),
('Alimenticio'),
('Tv'),
('Computador');
CREATE TABLE TB_CLIENTES(
 ID_CLI INT PRIMARY KEY AUTO_INCREMENT,
 NOME_CLI VARCHAR(100),
 END_CLI VARCHAR(100),
 N_CLI VARCHAR(4),
 BAIRRO_CLI VARCHAR(100),
 CIDADE_CLI VARCHAR(100),
 ID_EST INT, 
 CONSTRAINT FK_EST_CLI FOREIGN KEY(ID_EST) REFERENCES TB_ESTADO (ID_EST)
 ON  DELETE CASCADE ON UPDATE CASCADE 
);
CREATE TABLE TB_LOGIN(
 ID_LOG INT PRIMARY KEY AUTO_INCREMENT,
 LOGIN_LOG VARCHAR(100),
 SENHA_LOG VARCHAR(10),
 ID_CLI INT,
 CONSTRAINT FK_ FOREIGN KEY(ID_CLI) REFERENCES TB_CLIENTES(ID_CLI)
);
INSERT INTO TB_CLIENTES (NOME_CLI, END_CLI, N_CLI, BAIRRO_CLI, CIDADE_CLI, ID_EST)
VALUES ("Eliel Camara" , " RUA Marrocs", "105", "Monte Alegre", "TABOÃO DA SERRA", 25 );
INSERT INTO TB_LOGIN(LOGIN_LOG, SENHA_LOG, ID_CLI)
VALUES("ADM","123", 1);



-- select * from tb_login  where login_log = 'adm' and  senha_log ='123';


-- 
INSERT INTO TB_CLIENTES (NOME_CLI, END_CLI, N_CLI, BAIRRO_CLI, CIDADE_CLI, ID_EST)
VALUES ("JULIA SCHMITH GONCALVES" , " RUA DOS ANJOS", "1", "RECORD", "TABOÃO DA SERRA", 25 ),
       ("KAIQUE CAMPOS FERREIRA" , " RUA DOS ANJOS", "1", "RECORD", "TABOÃO DA SERRA", 25 ),
       ("KAIQUE FERRAZ DE JESUS" , " RUA DOS ANJOS", "1", "RECORD", "TABOÃO DA SERRA", 25 ),
       ("LORENNA MORAES MAIA" , " RUA DOS ANJOS", "1", "RECORD", "TABOÃO DA SERRA", 25),
       ("LUCAS BARBOZA DE JESUS" , " RUA DOS ANJOS", "1", "RECORD", "TABOÃO DA SERRA", 25 ),
       ("LUCAS KATO DE GODOI" , " RUA DOS ANJOS", "1", "RECORD", "TABOÃO DA SERRA", 25 ),
       ("LUCAS LOPES CUNHA" , " RUA DOS ANJOS", "1", "RECORD", "TABOÃO DA SERRA", 25 ),
       ("LUCCAS HIROSHI DE OLIVEIRA HINA" , " RUA DOS ANJOS", "1", "RECORD", "TABOÃO DA SERRA", 25 ),
       ("LUIZA CLARA SANTOS SILVA" , " RUA DOS ANJOS", "1", "RECORD", "TABOÃO DA SERRA", 25 ),
       ("MARIA CLARA DOS SANTOS" , " RUA DOS ANJOS", "1", "RECORD", "TABOÃO DA SERRA", 25 ),
       ("PEDRO HENRIQUE MENDES DE LIMA" , " RUA DOS ANJOS", "1", "RECORD", "TABOÃO DA SERRA", 25 ),
       ("PEDRO HENRIQUE SOUZA DE MESQUIT" , " RUA DOS ANJOS", "1", "RECORD", "TABOÃO DA SERRA", 25 ),
       ("PHELIPE FERREIRA SOARES" , " RUA DOS ANJOS", "1", "RECORD", "TABOÃO DA SERRA", 25 ),
       ("RAFAEL SEIDI SUZUKI TOMITT" , " RUA DOS ANJOS", "1", "RECORD", "TABOÃO DA SERRA", 25 ),
       ("TAMIRES AMERICO" , " RUA DOS ANJOS", "1", "RECORD", "TABOÃO DA SERRA", 25 ),
       ("TATIANA PEREIRA DE SOUZA" , " RUA DOS ANJOS", "1", "RECORD", "TABOÃO DA SERRA", 25 ),
       ("VICTORIA DOS SANTOS" , " RUA DOS ANJOS", "1", "RECORD", "TABOÃO DA SERRA", 25 ),
       ("VINICIUS FERREIRA MELO" , " RUA DOS ANJOS", "1", "RECORD", "TABOÃO DA SERRA", 25 );
       
       
       SELECT * FROM TB_CLIENTES;
       
       SELECT TB_CLIENTES.ID_CLI AS CODIGO,
			  TB_CLIENTES.NOME_CLI AS NOME,
			  TB_CLIENTES.END_CLI AS ENDEREÇO,
			  TB_CLIENTES.N_CLI AS NUMERO,
              TB_CLIENTES.BAIRRO_CLI AS BAIRRO,
              TB_CLIENTES.CIDADE_CLI AS CIDADE,
              TB_ESTADO.NOME_EST AS  ESTADO
         FROM TB_CLIENTE INNER JOIN TB_ESTADO
         ON TB_CLIENTE.ID_EST = TB_ESTADO.ID_EST;
              
              
       



